alias ll='ls -alFh'
alias kk='ls -alFh'
alias ..="cd ../"
alias ...="cd ../../"
alias ....="cd ../../../"
alias sshAli='ssh root@47.92.222.162'
alias gst='git status'
alias gl='git log'
alias cpwd='pwd|pbcopy'
alias grepflict='grep -lr "<<<<<<" .'
alias grep='grep --color=auto'
alias sc='screen'
alias god="sh dev_build.sh ; sh ./output/dev_bootstrap.sh"
alias fisdev='fisb release -w -d  dev'
alias dc='docker-compose'
alias fisclr='fisb release -c'
alias fisdevo='fisb release -cDoumpd luonan_local'
alias ifcfg='ifconfig | grep netmask'
alias inspector='node-inspector -p=8089'
alias ndebug='node --debug=5859 ./bin/www'
alias kpt='sh ~/Sites/shell_playground/killByPort.sh'
alias make_commit='sh ~/Sites/shell_playground/commit.sh'
alias make_update='sh ~/Sites/shell_playground/resetproject.sh'
alias kdv='~/Sites/shell_playground/killDlv.sh'
alias toDocker='docker exec -it'
alias gti='git'
alias gut='git'
alias gst='git st'
alias j='z'